let five = 5;
let eight = 8;
let cow = "tipsy";
let ten = 10;
console.log(five * eight);
console.log(five * cow);
console.log(ten + cow);
console.log(eight - ten);
console.log(eight + cow + ten);
console.log(ten + "ten");